# status basic
set -g status on
set -g status-interval 5
set -g status-position bottom
set -g status-justify left

# colors
set -g status-style "bg=colour235,fg=colour250"

# left
set -g status-left-length 50
set -g status-left-style "bg=colour31,fg=colour231,bold"
set -g status-left "  #S  | #[fg=colour250]#H  "

# windows
setw -g window-status-format " #[fg=colour244]#I:#W "
setw -g window-status-current-format "#[bg=colour67,fg=colour231,bold] #I:#W "

# right
set -g status-right-length 80
set -g status-right "#[fg=colour244]%Y-%m-%d #[fg=colour250]%H:%M "
