set -g status on
set -g status-interval 5

set -g status-left-length 40
set -g status-right-length 80

set -g status-left "#S | #H"
set -g status-right "%Y-%m-%d %H:%M"

setw -g window-status-format "#I:#W"
setw -g window-status-current-format "[#I:#W]"

