# status basic
set -g status on
set -g status-interval 5
set -g status-position bottom
set -g status-justify left

# colors
set -g status-style "bg=colour240,fg=colour255"

# left
set -g status-left-length 50
set -g status-left-style "bg=colour33,fg=colour255,bold"
set -g status-left "  #S  | #[fg=colour250]#H  "

# windows
setw -g window-status-format " #[fg=colour252]#I:#W "
setw -g window-status-current-format "#[bg=colour75,fg=colour16,bold] #I:#W "

# right
set -g status-right-length 80
set -g status-right "#[fg=colour252]%Y-%m-%d #[fg=colour255]%H:%M "
